### ISSUE TITLE
老哥求助 抓取的评论无法正常以.csv文件保存下来

### ISSUE THREAD

**Issue by Ppinnacle** [fengzi1013/Sentiment-Analysis-for-Douyin#1]
![image](https://user-images.githubusercontent.com/95207807/211773086-d66c9bbd-5022-4a4e-9a2f-de43d9f4401d.png)
![image](https://user-images.githubusercontent.com/95207807/211773165-c40e9ae4-26f8-41f1-a154-d9aa27f26f0b.png)
无论抓多少都是空表格

**Comment by fengzi1013** [comment]
debug试试。
